# Generated by Django 5.0.6 on 2024-06-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
        migrations.RenameModel(
            old_name='ResourceTypes',
            new_name='ResourceType',
        ),
    ]
